### ISSUE TITLE
a error

### ISSUE THREAD

**Issue by yancie-yjr** [XCRobert/Labelme2Coco#4]
Traceback (most recent call last):
  File "/home/hustget/labelme2coco/coco.py", line 11, in <module>
    labelme2coco.convert(labelme_folder, save_json_path)
  File "/media/hustget/E240392A40390737/labelme2coco/labelme2coco/__init__.py", line 14, in convert
    labelme2coco(labelme_folder, save_json_path)
  File "/media/hustget/E240392A40390737/labelme2coco/labelme2coco/labelme2coco.py", line 34, in __init__
    self.save_json()
  File "/media/hustget/E240392A40390737/labelme2coco/labelme2coco/labelme2coco.py", line 146, in save_json
    self.data_transfer()
  File "/media/hustget/E240392A40390737/labelme2coco/labelme2coco/labelme2coco.py", line 50, in data_transfer
    self.annotations.append(self.annotation(points, label, num))
  File "/media/hustget/E240392A40390737/labelme2coco/labelme2coco/labelme2coco.py", line 85, in annotation
    annotation['bbox'] = list(map(float, self.getbbox(points)))
  File "/media/hustget/E240392A40390737/labelme2coco/labelme2coco/labelme2coco.py", line 114, in getbbox
    return self.mask2box(mask)
  File "/media/hustget/E240392A40390737/labelme2coco/labelme2coco/labelme2coco.py", line 122, in mask2box
    left_top_r = np.min(rows)  # y
  File "<__array_function__ internals>", line 6, in amin
  File "/home/hustget/miniconda2/envs/open-mmlab/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2831, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/home/hustget/miniconda2/envs/open-mmlab/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

Process finished with exit code 1

**Comment by fcakyon** [comment]
@yancie-yjr use https://github.com/fcakyon/labelme2coco for improved version
